version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs-app:
    build: .
    ports:
      - "4500:4500"
    environment:
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_DB: mydatabase
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
    depends_on:
      - postgres

volumes:
  postgres-data: